-- ============================================================
--  Devoirati — Schéma de base de données
--
--  ⛔ CE FICHIER N'EST PLUS LA RÉFÉRENCE ET NE DOIT PAS ÊTRE EXÉCUTÉ.
--
--  À la suite de la revue d'architecture de Dhia, la conception a été
--  détaillée dans le DOSSIER DE PLANIFICATION :
--
--     docs/README.md .......... sommaire + réponse aux 14 points
--     docs/01-audit-existant.md ............ audit des tables existantes
--     docs/02-dictionnaire-donnees.md ...... toutes les tables & colonnes
--     docs/04-migration-sauvegarde-rollback.md .. script de migration réel
--
--  ⚠️ Aucune table ne doit être créée ou modifiée avant :
--     1) la validation de Dhia sur la partie base de données,
--     2) une sauvegarde complète de la base (voir doc 04).
-- ============================================================
